obj_file = "../models/apple.obj"
albedo_texture = "../textures/apple.png"
stroke_density = 2200
brush_size = 0.04
quantization = 8
background = [0.5, 0.5, 0.5]
saturation = 0.73
position = [0.0, -0.612, 0.0]
camera_position = [0.9, 0.9, 0.9]
