obj_file = "../models/strawberry.obj"
albedo_texture = "../textures/strawberry.png"
stroke_density = 500
brush_size = 0.08
quantization = 8
background = [1.0, 0.537, 0.537]
position = [0.0, -3.0, 0.0]
camera_position = [4.0, 4.0, 4.0]